categories:
 - design
 - graphic_design
 - illustration
 - web_development
 - ruby
 - php
 - python
 - typography
 - web_design
 - advertising
 - animation
 - art_direction
 - caligraphy
 - photography
 - cinematography
 - copywriting
 - consulting
 - creative_direction
 - digital_art
 - digital_imaging
 - fashion
 - fine_arts
 - film
 - motion_graphics
 - print_design
 - packaging_design
 - interface_design
 - information_architecture
 - user_experience
 - usability
